server:
  port: 7777

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:http: //127.0.0.1:8761/eureka

greeting:
  message: Welcome to the simple E-Commerce.

